### ISSUE TITLE
library initialization failed - unable to allocate file descriptor table - out of memory

### ISSUE THREAD

**Issue by itning** [zyyzyykk/kkTerminal#3]
command:
```shell
docker run -d --name kkterminal -p 3000:3000 zyyzyykk/kkterminal
```
docker version:
```shell
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:42:48 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:09 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
![image](https://github.com/user-attachments/assets/be483c0c-0806-4ff0-affd-e7efce2fd4fa)

**Comment by itning** [comment]
free -m
```shell
               total        used        free      shared  buff/cache   available
Mem:           31809       17326        1253         402       14085       14482
Swap:           5119        5119           0

```

**Comment by zyyzyykk** [comment]
Did you upload large size files?

**Comment by itning** [comment]
it's the docker container that reports an error directly on startup, haven't done anything else yet

**Comment by itning** [comment]
https://github.com/user-attachments/assets/5faabf11-9c8d-479b-8042-8faa32ee3afc

**Comment by zyyzyykk** [comment]
Can you show me the result of `ulimit -n`

**Comment by itning** [comment]
> ulimit -n

1024

**Comment by zyyzyykk** [comment]
add these parameters in docker command: `--ulimit nofile=65535:65535 --ulimit nproc=65535:65535`

**Comment by itning** [comment]
can not work
![image](https://github.com/user-attachments/assets/585c1603-3078-4345-8148-2f0ee6dc25aa)

**Comment by zyyzyykk** [comment]
From `free -m`, your swap has been fully depleted, possibly due to excessive server load.

Can other docker containers be run?

**Comment by zyyzyykk** [comment]
add this parameters in docker command: ` --privileged=true`

**Comment by itning** [comment]
> Can other docker containers be run?

![image](https://github.com/user-attachments/assets/115eefde-8bac-428e-af4a-903deaba8f29)

**Comment by itning** [comment]
> --privileged=true

![image](https://github.com/user-attachments/assets/9ed3b448-e0c5-4692-8a12-10bd9f88e5c8)

**Comment by itning** [comment]
![image](https://github.com/user-attachments/assets/cd0d88d0-7e8b-4aea-80d9-c9f7656991c3)

**Comment by zyyzyykk** [comment]
try to exec `ulimit -n 65535`

**Comment by itning** [comment]
> ulimit -n 65535

![image](https://github.com/user-attachments/assets/7919296d-78d5-4875-9130-c2e73780fd27)

**Comment by zyyzyykk** [comment]
Refer to this link: https://blog.csdn.net/xiaochenXIHUA/article/details/142691325
