### ISSUE TITLE
支持切换字符集吗

### ISSUE THREAD

**Issue by ZiangGithub** [zyyzyykk/kkTerminal#4]
ssh登录后，支持切换字符集吗

**Comment by zyyzyykk** [comment]
暂时不支持，不过可以通过使用TCode结合切换字符集的命令快速切换

**Comment by ZiangGithub** [comment]
> 暂时不支持，不过可以通过使用TCode结合切换字符集的命令快速切换

可以写个具体例子不，看的不是很明白。。比如切换成gbk

**Comment by zyyzyykk** [comment]
> > 暂时不支持，不过可以通过使用TCode结合切换字符集的命令快速切换
> 
> 可以写个具体例子不，看的不是很明白。。比如切换成gbk

我可能理解错了，应该是无法使用GBK字符集的，会出现乱码，比如在Windows系统直接运行 `kkTerminal.jar`，中文输入会乱码

**Comment by ZiangGithub** [comment]
> > > 暂时不支持，不过可以通过使用TCode结合切换字符集的命令快速切换
> > 
> > 
> > 可以写个具体例子不，看的不是很明白。。比如切换成gbk
> 
> 我可能理解错了，应该是无法使用GBK字符集的，会出现乱码，比如在Windows系统直接运行 `kkTerminal.jar`，中文输入会乱码

好的，请问下后续有精力搞一下这个么~~

**Comment by liushuai42** [comment]
<pre>
+---------+     http      +-------------+    ssh     +---------------+
| browser | <===========> | kk Terminal | <========> | remote server |
+---------+   websocket   +-------------+    sftp    +---------------+
Vue + Xterm              SpringBoot + SSHJ                Linux OS    
</pre>

@ZiangGithub 是 remote server 使用的 GBK 编码吗？估计需要添加一个参数来控制 SSHJ 来使用 GBK 编码。
我理解 SpringBoot 和 browser 部分可以继续使用 UTF-8 编码，无需额外的修改。

**Comment by ZiangGithub** [comment]
> +---------+     http      +-------------+    ssh     +---------------+
> | browser | <===========> | kk Terminal | <========> | remote server |
> +---------+   websocket   +-------------+    sftp    +---------------+
> Vue + Xterm              SpringBoot + SSHJ                Linux OS    
> @ZiangGithub 是 remote server 使用的 GBK 编码吗？估计需要添加一个参数来控制 SSHJ 来使用 GBK 编码。 我理解 SpringBoot 和 browser 部分可以继续使用 UTF-8 编码，无需额外的修改。

嗯嗯，是您理解的意思。我们这边环境linux服务器因为历史原因基本都是中文编码（gb2312，gbk），很扯淡。

**Comment by zyyzyykk** [comment]
@ZiangGithub 现在已经修改为建立连接时自动匹配服务器编码格式，下个release会更新

**Comment by ZiangGithub** [comment]
> @ZiangGithub @liushuai42 已发布最新版 **3.3.7**，问题已解决

刚刚试了，完美解决！感谢！！
