### ISSUE TITLE
宝塔面板配置证书后，访问一直提示Connecting to remote server ...

### ISSUE THREAD

**Issue by ccinoo** [zyyzyykk/kkTerminal#6]
你好：
     我在vps上通过容器部署了[kkTerminal](https://github.com/zyyzyykk/kkTerminal)，通过vps IP加3000端口访问正常。

1、但是通过宝塔面板配置证书和反向代理后，访问就一直提示“Connecting to remote server ...”如下图。

![image](https://github.com/user-attachments/assets/62f6d2af-8d97-4382-a8d6-f8f2d3530733)

2、反向代理代码如下：
`#PROXY-START/
location  ~* \.(gif|png|jpg|css|js|woff|woff2)$
{
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    expires 12h;
}
location /
{
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    
    add_header X-Cache $upstream_cache_status;
    
    #Set Nginx Cache
    
    	add_header Cache-Control no-cache;
}

#PROXY-END/`

**Comment by zyyzyykk** [comment]
应该还需要对websocket进行一些额外配置：
```
proxy_pass http://127.0.0.1:3000;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_read_timeout  36000s;
```

**Comment by ccinoo** [comment]
> 应该还需要对websocket进行一些额外配置：
> 
> ```
> proxy_pass http://127.0.0.1:3000;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header Host $host;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_http_version 1.1;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> proxy_read_timeout  36000s;
> ```

感谢回复：
增加配置后可以弹窗了，但是输入连接信息后，提示“Fail to connect remote server !”又弹出连接配置窗口。chrome开发者工具中查到如下报错：
`ssh.*****.xxx/:1 Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Bt.updateConfig (content.js:43:74765)
    at Bt.initConfig (content.js:43:74930)Understand this errorAI
ssh.*****.xxx/:1 Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at mt.updateConfig (textVoice.js:61:88304)
    at mt.initConfig (textVoice.js:61:88469)
    at async main (textVoice.js:179:2910)
    at async textVoice.js:179:3381Understand this errorAI
ssh.*****.xxx/:1 Error handling response: SyntaxError: Unexpected token '<', "<<<<<<< HE"... is not valid JSON
    at JSON.parse (<anonymous>)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/common.js:3:23336Understand this errorAI
ssh.*****.xxx/:1 Error handling response: SyntaxError: Unexpected token '<', "<<<<<<< HE"... is not valid JSON
    at JSON.parse (<anonymous>)
    at chrome-extension://ijllcpnolfcooahcekpamkbidhejabll/bundle/common.js:3:23336`
![image](https://github.com/user-attachments/assets/6a8c55ed-2b29-45e0-806a-7667ff444401)

**Comment by zyyzyykk** [comment]
可能需要分开配置：
```
location /socket {
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout  36000s;
}

location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

**Comment by zyyzyykk** [comment]
有url地址吗

**Comment by ccinoo** [comment]
> 有url地址吗

发您126邮箱了。

**Comment by zyyzyykk** [comment]
看起来应该是加密出错乱码了：
![image](https://github.com/user-attachments/assets/25bfa646-a080-4ddc-a87b-057ed9182c83)
部署的服务器是什么编码格式？

**Comment by ccinoo** [comment]
> 看起来应该是加密出错乱码了： ![image](https://private-user-images.githubusercontent.com/124498661/389179964-25bfa646-a080-4ddc-a87b-057ed9182c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNDU3NDYsIm5iZiI6MTczMjM0NTQ0NiwicGF0aCI6Ii8xMjQ0OTg2NjEvMzg5MTc5OTY0LTI1YmZhNjQ2LWEwODAtNGRkYy1hODdiLTA1N2VkOTE4MmM4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QwNzA0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODgyMjQ0ZDY1ZWMxYzdmOTM5MGEzMzA4NjYzNGMzNjc3M2MxY2VkNzEyYjE3MmUxZWJjZDIyOTc0Y2JjN2JlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.coJBPbupucrYpWs39LPW9JloobvPg8lwkp8IoIIVBRw) 部署的服务器是什么编码格式？

是要的这个吗？
`[root@ST-7fKqjw ~]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=`

**Comment by zyyzyykk** [comment]
应该是乱码了，你部署的服务器是什么编码格式的？
![image](https://github.com/user-attachments/assets/1ea6cf56-71c8-4a69-89c3-731c0ed63fce)

**Comment by zyyzyykk** [comment]
我刚刚更新了latest版本的镜像，你重新部署试一下

**Comment by ccinoo** [comment]
> 我刚刚更新了latest版本的镜像，你重新部署试一下

更新后也不行，但我部署到另外一台上是可以正常的。应该是我这台的个例问题，麻烦你了。

**Comment by zyyzyykk** [comment]
行，那就先这样了

**Comment by ccinoo** [comment]
> 行，那就先这样了

好的，感谢~
