### ISSUE TITLE
使用Tcode中的/C无法关闭窗口

### ISSUE THREAD

**Issue by chen2151643** [zyyzyykk/kkTerminal#7]
直接用网址访问terminal，使用Tcode中的/C无法关闭窗口，但是用Tcode中的/O新建的窗口可以用/C关闭。

**Comment by zyyzyykk** [comment]
这是浏览器正常行为：
![image](https://github.com/user-attachments/assets/ac4bdf08-a1c3-4bae-b6c6-d5589e3debeb)
